extends: default
rules:
  document-start:
    present: false
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: false
  comments:
    ignore-shebangs: true
    min-spaces-from-content: 1
    require-starting-space: true
