services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.22.0@sha256:af827f25120c7a76c5b20bfb34f230353d44920ef7c55a9d7f3ae2aac9c51c94
    ports:
      - 13378:80
    volumes:
      - ./data/audiobooks:/audiobooks
      - ./data/metadata:/metadata
      - ./data/podcasts:/podcasts
      - ./data/config:/config
    environment:
      - TZ=Europe/Berlin
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "abs"
      glance.name: Audiobookshelf
      glance.icon: di:audiobookshelf
      glance.url: https://abs.quoll-ratio.ts.net
