---
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.20.0@sha256:106531342a5f150e0e3dcbb348f126a5c452ecc4274f162d31545194dbe4352a
    ports:
      - 13378:80
    volumes:
      - ./data/audiobooks:/audiobooks
      - ./data/podcasts:/podcasts
      - ./data/config:/config
      - ./data/metadata:/metadata
    environment:
      - TZ=Europe/Berlin
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "abs"
      glance.name: AudioBookShelf
      glance.icon: si:audiobookshelf
      glance.url: https://abs.quoll-ratio.ts.net
