services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.26.2@sha256:80f0005eeecb952605aa9674bc39a77849614b5ca461d06229ceec7642f96cdb
    ports:
      - 13378:80
    volumes:
      - ./data/audiobooks:/audiobooks
      - ./data/metadata:/metadata
      - ./data/podcasts:/podcasts
      - ./data/config:/config
    environment:
      - TZ=Europe/Berlin
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "abs"
      glance.name: Audiobookshelf
      glance.icon: di:audiobookshelf
      glance.url: https://abs.quoll-ratio.ts.net
