services:
  navidrome:
    image: docker.io/deluan/navidrome:0.55.2@sha256:3a66e262b7ea836faa06c08ad5b32076c49e9e63e2fa4de10080c8e9be9f0846
    ports:
      - "4533:4533"
    restart: unless-stopped
    volumes:
      - "./data/data:/data"
      - "./data/music:/music:ro"
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "music"
      glance.name: Navidrome
      glance.icon: si:navidrome
      glance.url: https://music.quoll-ratio.ts.net
