services:
  navidrome:
    image: docker.io/deluan/navidrome:0.58.0@sha256:2ae037d464de9f802d047165a13b1c9dc2bdbb14920a317ae4aef1233adc0a3c
    ports:
      - "4533:4533"
    restart: unless-stopped
    volumes:
      - "./data/data:/data"
      - "./data/music:/music:ro"
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "music"
      glance.name: Navidrome
      glance.icon: di:navidrome
      glance.url: https://music.quoll-ratio.ts.net
