services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2025.7@sha256:e5bf3905955081dc4aae3b3980870c43ce6d8ffb880b5447addb3b3ba00f7bc0
    restart: unless-stopped
    privileged: true # Required for some hardware integrations
    volumes:
      - /dev:/dev
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8123:8123"
    environment:
      - TZ=Europe/Berlin
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8123"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "ha"
      tsdproxy.container_port: 8123
      glance.name: HomeAssistant
      glance.icon: di:home-assistant
      glance.url: https://ha.quoll-ratio.ts.net
