services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2025.4@sha256:c9a4eefee167f674db4a51b1b7466339a5637978cee4df0269e5f41ff1614aaf
    restart: unless-stopped
    privileged: true # Required for some hardware integrations
    volumes:
      - /dev:/dev
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8123:8123"
    environment:
      - TZ=Europe/Berlin
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8123"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "ha"
      tsdproxy.container_port: 8123
      glance.name: HomeAssistant
      glance.icon: si:homeassistant
      glance.url: https://ha.quoll-ratio.ts.net
