services:
  broker:
    container_name: paperless-redis
    image: docker.io/valkey/valkey:8-alpine@sha256:0d27f0bca0249f61d060029a6aaf2e16b2c417d68d02a508e1dfb763fa2948b4
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - ./data:/data
    labels:
      glance.hide: true
      glance.parent: paperless
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.18@sha256:6dbe57d8198fa117158ba9e867e2d45280b65e9c37ea54c1df7b34c4085a564c
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - "8000:8000"
    volumes:
      - ./data/data:/usr/src/paperless/data
      - ./data/media:/usr/src/paperless/media
      - ./data/export:/usr/src/paperless/export
      - ./data/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "paper"
      glance.id: paperless
      glance.name: Papaerless-ngx
      glance.icon: di:paperless
      glance.url: https://paper.quoll-ratio.ts.net
