services:
  broker:
    container_name: paperless-redis
    image: docker.io/valkey/valkey:8-alpine@sha256:d827e7f7552cdee40cc7482dbae9da020f42bc47669af6f71182a4ef76a22773
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - ./data:/data
    labels:
      glance.hide: true
      glance.parent: paperless
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.18@sha256:3421ebe06ed27662d014046cf5089e612de853aae0c676a2bc72f73b38080e57
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - "8000:8000"
    volumes:
      - ./data/data:/usr/src/paperless/data
      - ./data/media:/usr/src/paperless/media
      - ./data/export:/usr/src/paperless/export
      - ./data/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "paper"
      glance.id: paperless
      glance.name: Papaerless-ngx
      glance.icon: di:paperless
      glance.url: https://paper.quoll-ratio.ts.net
