services:
  broker:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine@sha256:f3959d30d4aa6df4fe7468c6b17d103e56f0fc7a4246f32d8106991b3665cdb9
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - ./data:/data
    labels:
      glance.hide: true
      glance.parent: searxng
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.15@sha256:39b337e73c978238f0b529baf42f1b59b65d17eed35cd61bc1ccbbf779b5d58b
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - "8000:8000"
    volumes:
      - ./data/data:/usr/src/paperless/data
      - ./data/media:/usr/src/paperless/media
      - ./data/export:/usr/src/paperless/export
      - ./data/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "paper"
      glance.id: searxng
      glance.name: Searxng
      glance.icon: di:paperless
      glance.url: https://paper.quoll-ratio.ts.net
