---
services:
  tsdproxy:
    image: ghcr.io/almeidapaulopt/tsdproxy:1.4.6@sha256:37606ffcb651e3402e1216aa6dbef2f451598ef6df0c207815618ddcf7e21d60
    container_name: tsdproxy
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./config/:/config
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
    ports:
      - "8080:8080"
    environment:
      - STATE_DIRECTORY="/data"
