services:
  adguard:
    container_name: adguard
    image: docker.io/adguard/adguardhome:v0.107.59@sha256:5d5e3aef39a8c8906a324f0c2da0a6123929e459b57c1e3f05e401dca5c7bf02
    restart: unless-stopped
    ports:
      - 53:53/tcp # plain dns over tcp
      - 53:53/udp # plain dns over udp
      - 8088:80/tcp # http web interface
      - 3000:3000/tcp # initial setup web interface
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data/work:/opt/adguardhome/work
      - ./config:/opt/adguardhome/conf
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "ad"
      tsdproxy.container_port: 80 # comment for the initial setup only
      glance.name: Adguard
      glance.icon: si:adguard
      glance.url: https://ad.quoll-ratio.ts.net
