---
services:
  unbound:
    container_name: unbound
    image: docker.io/klutchell/unbound:latest@sha256:bbd1895ec29743901ee110206d62ad39a599eeac50f0c32fdc07ca085ae4e794
    restart: unless-stopped
    volumes:
      - ./custom.conf.d:/etc/unbound/custom.conf.d:ro
    ports:
      - "5353:53/tcp"
      - "5353:53/udp"
    depends_on:
      - valkey
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "unbound"
      glance.name: Unbound
      glance.url: https://unbound.quoll-ratio.ts.net

  valkey:
    container_name: valkey
    image: docker.io/valkey/valkey:8-alpine@sha256:0fae58181c223280867e8b6d9d5fa29fca507770aeb6819f36d059cab73fa2fd
    restart: unless-stopped
    volumes:
      - ./valkey/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
