# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  base_url: "https://search.quoll-ratio.ts.net"
  secret_key: "superultrasecretkey" # change this!
  limiter: false # can be disabled for a private instance
  image_proxy: true
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0
