---
services:
  portainer:
    image: docker.io/portainer/portainer-ce:lts@sha256:60ce692bb8b59963669294b751b39c82b4159fdaba24f68c06ee957d6c27a5ce
    command: --http-enabled
    restart: unless-stopped
    container_name: portainer
    ports:
      - "9443:9443"
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "portainer"
      tsdproxy.container_port: 9000
      glance.name: Portainer
      glance.icon: si:portainer
      glance.url: https://portainer.quoll-ratio.ts.net

volumes:
  portainer_data:
