services:
  portainer:
    image: docker.io/portainer/portainer-ce:lts@sha256:449202d765d28ec443c1657fc1121aff92b8afcee6b58bcea36e1f0e81e8297c
    command: --http-enabled
    restart: unless-stopped
    container_name: portainer
    ports:
      - "9443:9443"
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "portainer"
      tsdproxy.container_port: 9000
      glance.name: Portainer
      glance.icon: di:portainer
      glance.url: https://portainer.quoll-ratio.ts.net
volumes:
  portainer_data:
