version: "3.7"

services:
  portainer:
    image: docker.io/portainer/portainer-ce:lts@sha256:99c3047d44991af08f2a34df16e69ae2654bee43444b2e9857aa6b5864c4f602
    restart: unless-stopped
    container_name: portainer
    ports:
      - "9443:9443"
    volumes:
      - portainer_data:/data
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "portainer"

volumes:
  portainer_data:
