services:
  portainer:
    image: docker.io/portainer/portainer-ce:lts@sha256:224a378fbc5ae579dc9d570c5ca2e5e981a4a003c8d7c2c5b5e482af97c2f87c
    command: --http-enabled
    restart: unless-stopped
    container_name: portainer
    ports:
      - "9443:9443"
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "portainer"
      tsdproxy.container_port: 9000
      glance.name: Portainer
      glance.icon: di:portainer
      glance.url: https://portainer.quoll-ratio.ts.net
volumes:
  portainer_data:
