services:
  beszel:
    image: docker.io/henrygd/beszel:0.12@sha256:64d9c702dcee96c19099978941290dc7f99cf04e1c96c32cac4339020f9bda56
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "stats"
      glance.id: beszel
      glance.name: Beszel
      glance.icon: di:beszel
      glance.url: https://stats.quoll-ratio.ts.net
  beszel-agent:
    image: docker.io/henrygd/beszel-agent:0.12@sha256:eb33fcf2a49f3694d0088dcd23a34e2d5ad3c3d575d97aca6a1d3394faada51a
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./beszel_socket:/beszel_socket
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
    environment:
      LISTEN: /beszel_socket/beszel.sock
      # Do not remove quotes around the key
      KEY: 'UPDATE WITH YOUR PUBLIC KEY (copy from "Add system" dialog)'
    labels:
      glance.hide: true
      glance.parent: beszel
