services:
  beszel:
    image: docker.io/henrygd/beszel:0.11@sha256:0579352cd2c90e97d927bf5f450af5ccbc04e69decb0a84b4cc1fe9126c40ce1
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "stats"
      glance.id: beszel
      glance.name: Beszel
      glance.icon: di:beszel
      glance.url: https://stats.quoll-ratio.ts.net
  beszel-agent:
    image: docker.io/henrygd/beszel-agent:0.11@sha256:7ad7ddde5c6fffa57a85318c24322bc9100ee01c85c5f7189d229051b05fe7e2
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./beszel_socket:/beszel_socket
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
    environment:
      LISTEN: /beszel_socket/beszel.sock
      # Do not remove quotes around the key
      KEY: 'UPDATE WITH YOUR PUBLIC KEY (copy from "Add system" dialog)'
    labels:
      glance.hide: true
      glance.parent: beszel
