services:
  stirling-pdf:
    image: docker.io/stirlingtools/stirling-pdf:1.3.2-ultra-lite@sha256:5c2a328a22ba9907e464569fbc89ea055ae01b37b0f98de2a7db7d950c2e68f3
    ports:
      - '8083:8080'
    volumes:
      - ./StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - ./StirlingPDF/extraConfigs:/configs
      - ./StirlingPDF/customFiles:/customFiles/
      - ./StirlingPDF/logs:/logs/
      - ./StirlingPDF/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "pdf"
      glance.name: StirlingPDF
      glance.icon: di:stirling-pdf
      glance.url: https://pdf.quoll-ratio.ts.net
