services:
  glance:
    container_name: glance
    image: docker.io/glanceapp/glance:v0.7.10@sha256:65b20e4405611abca17a70f6c3c7b8fdb3ce6ff0179a32c35dd84d77db624db7
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
    ports:
      - 8082:8080
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "home"
      glance.name: Glance
      glance.icon: di:glance
      glance.url: https://home.quoll-ratio.ts.net
