services:
  glance:
    container_name: glance
    image: docker.io/glanceapp/glance:v0.7.9@sha256:6e14662ffe83d4bf4e09314d27ee233d51f3ed2dc7322c4d4b18c929177c4117
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
    ports:
      - 8082:8080
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "home"
      glance.name: Glance
      glance.icon: di:glance
      glance.url: https://home.quoll-ratio.ts.net
