services:
  gonic:
    image: ghcr.io/sentriz/gonic@sha256:fc7f3dee29c97be82f0558080637c61ef418437dd4ec760cb7a802a0efe38c20
    environment:
      - TZ=Europe/Berlin
    ports:
      - 4747:80
    volumes:
      - ./data/data:/data
      - ./data/music:/music:ro # your music
      - ./data/podcasts:/podcasts # your podcasts
      - ./data/playlists:/playlists # your playlists
      - ./data/cache:/cache # transcode / covers / etc cache dir
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "gonic"
      glance.name: Gonic
      glance.icon: di:gonic
      glance.url: https://gonic.quoll-ratio.ts.net
