services:
  gonic:
    image: ghcr.io/sentriz/gonic@sha256:32c400a21b107bc3b87a49ec9af591a37d7f9cc03ee83d68a379ee76bb716607
    environment:
      - TZ=Europe/Berlin
    ports:
      - 4747:80
    volumes:
      - ./data/data:/data
      - ./data/music:/music:ro # your music
      - ./data/podcasts:/podcasts # your podcasts
      - ./data/playlists:/playlists # your playlists
      - ./data/cache:/cache # transcode / covers / etc cache dir
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "gonic"
      glance.name: Gonic
      glance.icon: di:gonic
      glance.url: https://gonic.quoll-ratio.ts.net
